# Do not obfuscate or optimize, only shrink
-dontobfuscate
-dontoptimize

-dontwarn

# Keep the special static methods that are required in enumeration classes.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Keep all constructors of all classes
-keepclassmembers class * {
    public <init>(...);
}

-keepparameternames
-renamesourcefileattribute SourceFile
-keepattributes Signature,Exceptions,*Annotation*,
                InnerClasses,PermittedSubclasses,EnclosingMethod,
                Deprecated,SourceFile,LineNumberTable

# Database drivers. Keep all implementations of java.sql.Driver.
-keep class * extends java.sql.Driver

# Keep entry points of minecraft plugins
-keep class * extends org.bukkit.plugin.java.JavaPlugin

# Keep all config sections
-keep class * implements **.bbconfigmapper.sections.IConfigSection

# Keep the reflection helper (it's instantiated through reflection by the factory)
-keep class **.bbreflect.ReflectionHelper

# Keep event handlers
-keepclassmembers class ** {
    @org.bukkit.event.EventHandler public *;
}