# ______  __           _________________      _____       ______
#   ___  / / /__________ ______  /_  ____/_____ __  /______ ___  /____________ _
#   __  /_/ /_  _ \  __ `/  __  /_  /    _  __ `/  __/  __ `/_  /_  __ \_  __ `/
#   _  __  / /  __/ /_/ // /_/ / / /___  / /_/ // /_ / /_/ /_  / / /_/ /  /_/ /
#   /_/ /_/  \___/\__,_/ \__,_/  \____/  \__,_/ \__/ \__,_/ /_/  \____/_\__, /
#                                                                      /____/
#
# HeadCatalog - Developed by BlvckBytes <blvckbytes@gmail.com>
# Repository - https://github.com/BlvckBytes/HeadCatalog
# ASCII-Art - https://patorjk.com/software/taag/#p=display&f=Speed
#
# PRE-PROCESSOR-INPUT en_us.txt

catalogDisplay:
  # - current_page: Integer
  # - number_pages: Integer
  title: '@{RESULT-DISPLAY-TITLE}'
  items:
    # - head_name: String
    # - head_category: String
    # - head_tags: List<String>
    # - head_base64_textures: String
    representative:
      type: PLAYER_HEAD
      name$: '"&6" & head_name'
      textures$: 'head_base64_textures'
      lore$:
        - '"&7Category: &e" & head_category'
        - '"&7Tags:"'
        - |
          map(head_tags, (tag) => "&7- &e" & tag, "&cNo Tags")
    previousPage:
      type: PLAYER_HEAD
      textures$: 'lut["textures"][if current_page > 1 then "ARROW_LEFT" else "ARROW_LEFT_RED"]'
      name$: 'if current_page > 1 then @{PREVIOUS-PAGE-NAME-HAS} else @{PREVIOUS-PAGE-NAME-HAS-NOT}'
      lore$:
        - '" "'
        - '@{ANY-CONTROL-LORE-SPACER}'
        - '@{PREVIOUS-PAGE-LORE-LEFT-CLICK-DESCRIPTION}'
        - '@{PREVIOUS-PAGE-LORE-RIGHT-CLICK-DESCRIPTION}'
        - '@{ANY-CONTROL-LORE-SPACER}'
    nextPage:
      type: PLAYER_HEAD
      textures$: 'lut["textures"][if current_page < number_pages then "ARROW_RIGHT"
        else "ARROW_RIGHT_RED"]'
      name$: 'if current_page < number_pages then @{NEXT-PAGE-NAME-HAS} else @{NEXT-PAGE-NAME-HAS-NOT}'
      lore$:
        - '" "'
        - '@{ANY-CONTROL-LORE-SPACER}'
        - '@{NEXT-PAGE-LORE-LEFT-CLICK-DESCRIPTION}'
        - '@{NEXT-PAGE-LORE-RIGHT-CLICK-DESCRIPTION}'
        - '@{ANY-CONTROL-LORE-SPACER}'
    # is_valid: Boolean
    # search_query: String
    anvilInputItem:
      type: PURPLE_TERRACOTTA
      # Keep this as-is, otherwise the input will not persist when navigating pages!
      name$: 'search_query'
    # is_valid: Boolean
    # search_query: String
    anvilResultItem:
      type: PURPLE_TERRACOTTA
      name$: 'if is_valid then @{ANVIL-ITEM-NAME-VALID} else @{ANVIL-ITEM-NAME-INVALID}'
      lore$:
        - '" "'
        - '@{ANY-CONTROL-LORE-SPACER}'
        - '@{ANVIL-ITEM-LORE-DESCRIPTION}'
        - '@{ANY-CONTROL-LORE-SPACER}'
        - '@{ANVIL-ITEM-LORE-INPUT}'
        - '@{ANY-CONTROL-LORE-SPACER}'
    filler:
      type: BLACK_STAINED_GLASS_PANE
      name: " "

lut:
  textures:
    ARROW_LEFT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU1MGI3Zjc0ZTllZDc2MzNhYTI3NGVhMzBjYzNkMmU4N2FiYjM2ZDRkMWY0Y2E2MDhjZDQ0NTkwY2NlMGIifX19'
    ARROW_LEFT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg0ZjU5NzEzMWJiZTI1ZGMwNThhZjg4OGNiMjk4MzFmNzk1OTliYzY3Yzk1YzgwMjkyNWNlNGFmYmEzMzJmYyJ9fX0='
    ARROW_RIGHT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTYzMzlmZjJlNTM0MmJhMThiZGM0OGE5OWNjYTY1ZDEyM2NlNzgxZDg3ODI3MmY5ZDk2NGVhZDNiOGFkMzcwIn19fQ=='
    ARROW_RIGHT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmNmZTg4NDVhOGQ1ZTYzNWZiODc3MjhjY2M5Mzg5NWQ0MmI0ZmMyZTZhNTNmMWJhNzhjODQ1MjI1ODIyIn19fQ=='
