# ______  __           _________________      _____       ______
# ___  / / /__________ ______  /_  ____/_____ __  /______ ___  /____________ _
# __  /_/ /_  _ \  __ `/  __  /_  /    _  __ `/  __/  __ `/_  /_  __ \_  __ `/
# _  __  / /  __/ /_/ // /_/ / / /___  / /_/ // /_ / /_/ /_  / / /_/ /  /_/ /
# /_/ /_/  \___/\__,_/ \__,_/  \____/  \__,_/ \__/ \__,_/ /_/  \____/_\__, /
# /____/
# HeadCatalog - Developed by BlvckBytes <blvckbytes@gmail.com>
# (ascii-art: https://patorjk.com/software/taag/#p=display&f=Speed&t=HeadCatalog)

command:
  name: "headcatalog"
  aliases:
    - hc
  description: Opens the head catalog
