# ______  __           _________________      _____       ______
# ___  / / /__________ ______  /_  ____/_____ __  /______ ___  /____________ _
# __  /_/ /_  _ \  __ `/  __  /_  /    _  __ `/  __/  __ `/_  /_  __ \_  __ `/
# _  __  / /  __/ /_/ // /_/ / / /___  / /_/ // /_ / /_/ /_  / / /_/ /  /_/ /
# /_/ /_/  \___/\__,_/ \__,_/  \____/  \__,_/ \__/ \__,_/ /_/  \____/_\__, /
# /____/                                                             /____/
# HeadCatalog - Developed by BlvckBytes <blvckbytes@gmail.com>
# (ascii-art: https://patorjk.com/software/taag/#p=display&f=Speed&t=HeadCatalog)

command:
  name: "headcatalog"
  aliases:
    - hc
  description: Opens the head catalog

gui:
  representative:
    type: PLAYER_HEAD
    textures$: 'skin_url_to_base64(head.skinUrl)'
    name$: '"&8» &d" & head.name & " &8«"'
    lore$:
      - '" "'
      - '"&7Categories:"'
      - 'iter_map(head.categories, (category) => "&8➥ &d" & title_case(category), "&cNo Categories")'
      - '" "'
      - '"&7Tags:"'
      - 'iter_map(head.tags, (tag) => "&8➥ &d" & title_case(tag), "&cNo Tags")'
      - '" "'
      - '"&7Updated: &d" & date_format(head.updatedAt ?? head.createdAt, "date", lut["dateFormat"])'
      - '" "'
      - '"&7Click to &dreceive &7this head"'

source:
  # Every 24h will be the minimum value accepted
  updatePeriodSeconds: 86400
  apis:
    -
      urls:
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=alphabet'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=animals'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=blocks'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=decoration'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=food-drinks'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=humans'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=humanoid'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=miscellaneous'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=monsters'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=plants'
      dataType: JSON
      arrayExtractor$: 'result'
      itemMapper$: |
        make_head(
          item["name"],
          base64_to_skin_url(item["value"]),
          list_of("alphabet"),
          item["uuid"],
          split(item["tags"], ",")
        )

persistence:
  type: MySQL
  mySqlCredentials:
    host: 'localhost'
    port: 3306
    username: root
    password: mysql2001
    database: head_catalog
    table: head_model

# Lookup table for this file, used to centralize and deduplicate constants
lut:
  dateFormat: 'dd.MM.yyyy HH:mm:ss'