# ______  __           _________________      _____       ______
# ___  / / /__________ ______  /_  ____/_____ __  /______ ___  /____________ _
# __  /_/ /_  _ \  __ `/  __  /_  /    _  __ `/  __/  __ `/_  /_  __ \_  __ `/
# _  __  / /  __/ /_/ // /_/ / / /___  / /_/ // /_ / /_/ /_  / / /_/ /  /_/ /
# /_/ /_/  \___/\__,_/ \__,_/  \____/  \__,_/ \__/ \__,_/ /_/  \____/_\__, /
# /____/                                                             /____/
# HeadCatalog - Developed by BlvckBytes <blvckbytes@gmail.com>
# (ascii-art: https://patorjk.com/software/taag/#p=display&f=Speed&t=HeadCatalog)

command:
  name: "headcatalog"
  aliases:
    - hc
  description: Opens the head catalog
  errorMessages:
    malformedDouble$: 'lut["prefix"] & "&7The value &c" & value & " &7is not a valid &cdouble"'
    malformedFloat$: 'lut["prefix"] & "&7The value &c" & value & " &7is not a valid &cfloat"'
    malformedLong$: 'lut["prefix"] & "&7The value &c" & value & " &7is not a valid &clong"'
    malformedInteger$: 'lut["prefix"] & "&7The value &c" & value & " &7is not a valid &cinteger"'
    malformedUuid$: 'lut["prefix"] & "&7The value &c" & value & " &7is not a valid &cUUID"'
    malformedEnum$: |
      lut["prefix"] & "&7The value &c" & value & " &7is not one of (" &
      iter_cat(constant_names, (constant_name) => "&c" & constant_name, "&7, ", "&cNo values available") &
      "&7)"
    notAPlayer$: 'lut["prefix"] & "&7This command can only be executed as a &cplayer"'
    playerUnknown$: 'lut["prefix"] & "&7The player &c" & value & " &7has &cnot played &7on this server before"'
    playerNotOnline$: 'lut["prefix"] & "&7The player &c" & value & " &7is &cnot online"'
    internalError$: 'lut["prefix"] & "&4An internal error occurred"'

permissions:
  missingMessage$: 'lut["prefix"] & "&7You\sre lacking the permission &c" & permission'
  nodes:
    open: headcatalog.open
    request: headcatalog.request
    priceBypass: headcatalog.price-bypass

messages:
  inventoryFull$: 'lut["prefix"] & "&cYou have no more space left in your inventory"'
  requestedHeadPriceBypassed$: 'lut["prefix"] & "&7You received the head &d" & head.name'
  requestedHead$: |
    lut["prefix"] & (
      if head.price == 0 then
        "&7You received the &afree &7head &d" & head.name
      else
        "&7You bought the &7head &d" & head.name & " &7(&c-" & head.price & "$&7)"
    )
  missingBalance$: 'lut["prefix"] & "&7You\sre lacking &c" & head.price - balance & "$"'
  economyError$: 'lut["prefix"] & "&7An internal economy error occurred: &4" & error_message'

headCatalogUI:
  animating: true

  searchDebounceTicks: 5
  title: '&5HeadCatalog'

  representative:
    type: PLAYER_HEAD
    textures$: 'skin_url_to_base64(head.skinUrl)'
    name$: '"&8» &d" & head.name & " &8«"'
    lore$:
      - '" "'
      - '"&7Categories:"'
      - 'map(head.categories, (category) => "&8➥ &d" & title_case(category), "&cNo Categories")'
      - '" "'
      - '"&7Tags:"'
      - 'map(head.tags, (tag) => "&8➥ &d" & title_case(tag), "&cNo Tags")'
      - '" "'
      - '"&7Updated: &d" & date_format(head.lastUpdate, "date", lut["dateFormat"])'
      - '"&7Price: &d" & if head.price == 0 then "&afree" else head.price & "$"'
      - '" "'
      - '"&7Left click: &dRequest this head"'

  representativeAdmin:
    lore:
      - '&7Right click: &dEdit this head'
      - '&7Shift right click: &dDelete this head'

  filter:
    type: HOPPER
    name: '&8» &dFilter &8«'
    lore$:
      - '" "'
      - |
        map(filters, (entry) => (
          "&8➥ " & (if value(entry) then "&d" else "&7") & lut["headFilters"][key(entry)]
        ), "&cNo filters provided")
      - '" "'
      - '"&8● &7Click to &dcycle &7through filters"'

  back:
    type: PLAYER_HEAD
    textures$: 'lut["DOUBLE_ARROW_LEFT"]'
    name: '&8» &dBack &8«'
    lore:
      - ' '
      - '&8● &dExit &7from this screen'

  searchItem:
    type: PURPLE_TERRACOTTA
    name: ' '
    lore:
      - ' '
      - '&8● &7Type ahead to &dsearch &7for results'

  resultItem:
    type: PURPLE_TERRACOTTA
    name: '&8» &dSearch Query &8«'
    lore$:
      - '" "'
      - '"&8● &7Your query: &d" & search_text'

  previousPage:
    type: PLAYER_HEAD
    textures$: 'lut[if current_page > 1 then "ARROW_LEFT" else "ARROW_LEFT_RED"]'
    name$: '"&8» " & (if current_page > 1 then "&dPrevious Page" else "&cNo Previous Page") & " &8«"'
    lore$:
      - '" "'
      - |
        if current_page > 1 then list_of(
          "&8● &7Left click: &dPrevious Page",
          "&8● &7Right click: &dFirst Page"
        ) else list_of(
          "&8● &7Already on the &cfirst &7page"
        )

  currentPage:
    type: PAPER
    name$: '"&8» &dPage &5" & current_page & "&7/&5" & max(1, number_of_pages) & " &8«"'
    lore$:
      - '" "'
      - '"&8● &7Page size: &d" & page_size'
      - '"&8● &7Items total: &d" & number_of_pageables'

  nextPage:
    type: PLAYER_HEAD
    textures$: 'lut[if current_page < number_of_pages then "ARROW_RIGHT" else "ARROW_RIGHT_RED"]'
    name$: '"&8» " & (if current_page < number_of_pages then "&dNext Page" else "&cNo Next Page") & " &8«"'
    lore$:
      - '" "'
      - |
        if current_page < number_of_pages then list_of(
          "&8● &7Left click: &dNext Page",
          "&8● &7Right click: &dLast Page"
        ) else list_of(
          "&8● &7Already on the &clast &7page"
        )

  # FIXME: Move this to its own section!
  newButton:
    type: PLAYER_HEAD
    textures$: 'lut["GREEN_PLUS"]'
    name: '&8» &dAdd Tag &8«'
    lore:
      - ' '
      - '&8● &7Click to add a &dnew tag'

  # The pagination items are displayed in the player's inventory
  paginationSlots$: 'range(inventory_size, inventory_size + 26)'

  customItems:
    darkGlass:
      type: BLACK_STAINED_GLASS_PANE
      name: ' '

  slotContents:
    # Keep the pagination controls in the hotbar
    previousPage$: 'inventory_size + 29'
    currentPage$: 'inventory_size + 31'
    nextPage$: 'inventory_size + 33'
    filter$: 'inventory_size + 35'

    searchItem: 0
    back: 1
    resultItem: 2
    
    # FIXME: Move this to its own section!
    newButton$: 'inventory_size + 27'

    darkGlass$: |
      list_of(
        # Put a spacer in slot 2 of the anvil, since there's no back button, in order
        # to avoid the experience cost message to be displayed
        1,
        # Put spacers into unused hotbar slots
        inventory_size + 27,
        inventory_size + 28,
        inventory_size + 30,
        inventory_size + 32,
        inventory_size + 34,
        inventory_size + 35
      )

headEditUI:
  title: '&5Edit Head'
  numberOfRows: 3

  blockToggle:
    type$: 'if head.blocked then "RED_STAINED_GLASS_PANE" else "GREEN_STAINED_GLASS_PANE"'
    name$: '"&8» " & (if head.blocked then "&cBlocked" else "&aNot Blocked") & " &8«"'
    lore:
      - ' '
      - '&8● &7Click to &dtoggle &7its blocking status'

  categories:
    type: BOOK_AND_QUILL
    name: '&8» &dCategories &8«'
    lore:
      - ' '
      - '&8● &7Click to &dedit &7its category list'

  tags:
    type: PAPER
    name: '&8» &dTags &8«'
    lore:
      - ' '
      - '&8● &7Click to &dedit &7its tag list'

  name:
    type: NAME_TAG
    name: '&8» &dName &8«'
    lore:
      - ' '
      - '&8● &7Click to &dedit &7its name'

  price:
    type: GOLD_INGOT
    name: '&8» &dPrice &8«'
    lore:
      - ' '
      - '&8● &7Click to &dedit &7its price'

  tagRepresentative:
    type: PAPER
    name$: '"&8» &d" & value & "&8«"'
    lore:
      - ' '
      - '&8● &7Left click: &dEdit'
      - '&8● &7Right click: &dDelete'

  customItems:
    darkGlass:
      type: BLACK_STAINED_GLASS_PANE
      name: ' '

  slotContents:
    representative: 10
    blockToggle: 12
    categories: 13
    tags: 14
    name: 15
    price: 16
    darkGlass$: |
      flatten(
        range(0, 8),
        9, 11, 17,
        range(18, 26)
      )

source:
  updatePeriodSeconds: 86400
  apis:
    -
      urls:
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=alphabet'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=animals'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=blocks'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=decoration'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=food-drinks'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=humans'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=humanoid'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=miscellaneous'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=monsters'
        - 'https://minecraft-heads.com/scripts/api.php?tags=true&cat=plants'

      userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11'
      dataType: JSON
      arrayExtractor$: 'result'

      itemMapper$: |
        category = substring(url, r_index(url, "=") + 1)

        make_head(
          item["name"],
          base64_to_skin_url(item["value"]),
          item["uuid"],
          list_of(category),
          split(item["tags"], ","),
          lut["headPrices"]?[category] ?? lut["headPrices"]["fallback"]
        )

lut:
  prefix: '&5&lHC &8| '

  dateFormat: 'dd.MM.yyyy HH:mm:ss'

  DOUBLE_ARROW_LEFT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTE4YTJkZDViZWYwYjA3M2IxMzI3MWE3ZWViOWNmZWE3YWZlODU5M2M1N2E5MzgyMWU0MzE3NTU3MjQ2MTgxMiJ9fX0='
  ARROW_LEFT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTE4YTJkZDViZWYwYjA3M2IxMzI3MWE3ZWViOWNmZWE3YWZlODU5M2M1N2E5MzgyMWU0MzE3NTU3MjQ2MTgxMiJ9fX0='
  ARROW_LEFT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWRmNWMyZjg5M2JkM2Y4OWNhNDA3MDNkZWQzZTQyZGQwZmJkYmE2ZjY3NjhjODc4OWFmZGZmMWZhNzhiZjYifX19'
  ARROW_RIGHT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllY2NjNWMxYzc5YWE3ODI2YTE1YTdmNWYxMmZiNDAzMjgxNTdjNTI0MjE2NGJhMmFlZjQ3ZTVkZTlhNWNmYyJ9fX0='
  ARROW_RIGHT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJhZTg5ZTkyYWMzNjI2MzViYTNlOWZiN2MxMmI3ZGRkOWIzOGFkYjExZGY4YWExYWZmM2U1MWFjNDI4YTQifX19'
  GREEN_PLUS: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWZmMzE0MzFkNjQ1ODdmZjZlZjk4YzA2NzU4MTA2ODFmOGMxM2JmOTZmNTFkOWNiMDdlZDc4NTJiMmZmZDEifX19'

  headFilters:
    HEAD_EVERYWHERE: 'Everywhere'
    HEAD_NAME: 'Name'
    HEAD_CATEGORIES: 'Categories'
    HEAD_TAGS: 'Tags'

  headPrices:
    plants: 0
    alphabet: 125
    fallback: 250
